Repository LeaYeh/webserver, pull requests merged in 2025-03, with the labels that each got.

#169 [FIX] Make sure the connection be closed after respond
  include/kernel/RequestProcessor.hpp
  source/kernel/ConnectionHandler.cpp
  source/kernel/RequestProcessor.cpp
Labels: bug

#170 [FIX] Add consume body state to make sure no garbage left in the buffer
  include/defines.hpp
  include/kernel/RequestProcessor.hpp
  source/kernel/ConnectionHandler.cpp
  source/kernel/RequestProcessor.cpp
Labels: bug

#173 [FIX] Avoid temp file issues
  include/kernel/PostHandler.hpp
  include/kernel/UploadRecord.hpp
  include/shell/Request.hpp
  include/shell/UploadRecord2.hpp
  source/kernel/CgiExecutor.cpp
  source/kernel/PostHandler.cpp
  source/kernel/RequestProcessor.cpp
  source/kernel/UploadRecord.cpp
  source/shell/Request.cpp
  source/shell/UploadRecord2.cpp
Labels: bug

#174 [FIX] Fix corner case of client_max_body_size
  source/config/ConfigHttpBlock.cpp
  source/utils/utils.cpp
Labels: bug

#175 [FIX] Fix config corner cases from Lukas
  source/config/ConfigHttpBlock.cpp
  source/config/ConfigServerBlock.cpp
  source/shell/ResponseBuilder.cpp
  source/utils/IPAddress.cpp
Labels: bug, core

#182 [FIX] Fix analyzing multiple requests at the same time
  source/kernel/ConnectionHandler.cpp
  source/kernel/RequestProcessor.cpp
Labels: bug

#184 [FIX] Fix the normal chunked POST again
  source/kernel/PostHandler.cpp
  source/kernel/RequestProcessor.cpp
  source/shell/Request.cpp
Labels: bug, help wanted

#185 [FIX] Fix the get chunked incorrect format issue
  include/defines.hpp
  source/kernel/ConnectionHandler.cpp
  source/kernel/GetHandler.cpp
  source/kernel/RequestProcessor.cpp
  source/shell/Response.cpp
  source/shell/ResponseBuilder.cpp
Labels: bug

#188 [FIX] Make different ip cannot config with same port
  configs/invalid_port.conf
  include/config/Config.hpp
  source/config/Config.cpp
  source/main.cpp
Labels: enhancement

#190 [FIX] Update test demo page
  Makefile
  README.md
  configs/default.conf
  include/shell/Request.hpp
  source/kernel/GetHandler.cpp
  source/shell/Request.cpp
  www/html/delete.html
  www/html/footer.html
  www/html/get_basic.html
  www/html/get_mime.html
  www/html/mime/sample.css
  www/html/mime/sample.html
  www/html/mime/sample.js
  www/html/mime/sample.json
  www/html/mime/sample.png
  www/html/mime/sample.svg
  www/html/mime/sample.txt
  www/html/mime/sample.xml
  www/html/test_me.html
Labels: documentation, enhancement

#193 [FIX] Make validator do not check root and alias when redirect
  configs/redirect.conf
  source/config/ConfigLocationBlock.cpp
Labels: bug

#199 [FIX] Fix config format
  configs/limit_client_body.conf
  configs/limit_except_method.conf
  configs/multiple_port.conf
  configs/multiple_server.conf
  configs/redirect.conf
  configs/routes.conf
  configs/same_port.conf
  configs/siege.conf
  source/utils/IPAddress.cpp
Labels: documentation

#202 [FIX] Fix the non match host name logic
  source/kernel/RequestProcessor.cpp
Labels: bug

#205 [FIX] Make sure config parser cry with invalid route
  include/config/ConfigLocationBlock.hpp
  source/config/ConfigLocationBlock.cpp
Labels: bug

#208 [FIX] Fix the resource path logic
  configs/default.conf
  configs/different_hostname.conf
  configs/multiple_port.conf
  configs/multiple_server.conf
  configs/redirect.conf
  configs/root_and_alias.conf
  configs/routes.conf
  configs/same_port.conf
  include/config/ConfigLocationBlock.hpp
  include/utils/utils.hpp
  source/config/ConfigLocationBlock.cpp
  source/kernel/ARequestHandler.cpp
  source/utils/utils.cpp
Labels: bug
